### ISSUE TITLE
Background?

### ISSUE THREAD

**Issue by maplepy** [rklyz/MyRice#11]
Hey I love the background! Could we know where you find it or what did you type to get one like this please?

Much love

**Comment by maplepy** [comment]
Or if anyone knows what this style of painting is I'd love it

**Comment by rklyz** [comment]
I just found it randomly tbh.
but u can still search for tag: art, landscape, mountain, nature, etc

**Comment by rklyz** [comment]
found the artist of it
https://www.artstation.com/artwork/GWkzQ
